### PR TITLE
adding new Keyset to support the newtab_stats_daily table.  removing newtabs from impression_stats keyset.

### PR DESCRIPTION
**Pull request by tspurway**
adding new Keyset to support the newtab_stats_daily table.  removing newtabs from impression_stats keyset.

### CODE REVIEW

**Comment by tspurway** [comment]
Note that this PR relies on migrations in splice branch:

https://github.com/oyiptong/splice/tree/issue-15-tile-descriptions

**Comment by tspurway** [comment]
ping r? @oyiptong

**Comment by oyiptong** [comment]
r+

**Pull request closed without merging**
